### ISSUE TITLE
changing parameters of modi does not store

### ISSUE THREAD

**Issue by pvklink** [nielsfaber/alarmo#823]
### Alarmo Version

1.9.12

### HA Version

20231017.0.dev - latest

### Bug description

when i change the modi paramers in and out delays, the changed values dont store!
I use the latest docker on a rpi 4b with the latest os

All other applications works fine on this hass docker config
This is the only part that dont save.
Does it auto save, or do i get a save button, because i dont see one..

### Steps to reproduce

when i change all values for home, away night, the dissaper after the latest is changed and checking the first

**Comment by Eyco1981** [comment]
Can confirm. Same with my Alarmo installation.

**Comment by samtate** [comment]
Happens for me too. Is this from the latest update

**Comment by nielsfaber** [comment]
Could anyone check the HA log if any error is displayed here when making a change?
Changes should automatically be saved.
Is there any difference between changing a delay and enabling/disabling a mode?

**Comment by samtate** [comment]
Hi @nielsfaber I can enable/disable alarm modes and they will stick but I cannot change the entry/exit time or trigger time, as it will just revert to the previous value on refresh.

I do not see any errors in the browser console or in the home assistant logs. I looked on the /config/logs page under "Home Assistant Core", is that right?

**Comment by samtate** [comment]
I think I must have been able to change them in the past as my away mode was using non-default values.

I reinstalled the integration, having deleted it from the device list, and the issue still persists. Happens on mobile and desktop

**Comment by Eyco1981** [comment]
No error messages in the HA logs when changing the values.
Also only 3 messages in the system debug logs containing "Alarmo" - all error unrelated.
```
2023-11-02 18:11:42.081 INFO (MainThread) [homeassistant.setup] Setting up alarmo
2023-11-02 18:11:42.082 INFO (MainThread) [homeassistant.setup] Setup of domain alarmo took 0.0 seconds
2023-11-02 18:11:42.125 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.alarmo
```

**Comment by aurelmarius** [comment]
Same problem here. Just installed alarmo and can't set none of the delay settings.

**Comment by nielsfaber** [comment]
I can confirm the issue is caused by the HA 2023.11 update (I was on 2023.10 until today and could not reproduce this).
The issue is related to this change: https://github.com/home-assistant/frontend/pull/18168.
I will have to make some changes to Alarmo to restore functionality.

**Comment by nielsfaber** [comment]
I made a new release which should fix this issue.
@pvklink Could you please update and confirm the issue is solved for you now?

**Comment by Nicko33127** [comment]
Amazing work! I had the same issue, just tested it and it works now. Thank you!

**Comment by aurelmarius** [comment]
I can confirm, it is fixed now. Thanks a lot.

**Comment by lanieuwe** [comment]
No I installed te laterst version Firmware: 1.9.13 from HACS.
The problem is not fixed. I still cannot change the delay. The Alarmo site bar on the left hand site is v1.9.12 but the alarmo in the integration says firmware 1.9.13. That is strange....

**Comment by pvklink** [comment]
it works!thanks nielsVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Niels Faber ***@***.***> Datum: 04-11-2023  08:10  (GMT+01:00) Aan: nielsfaber/alarmo ***@***.***> Cc: peter van klink ***@***.***>, Mention ***@***.***> Onderwerp: Re: [nielsfaber/alarmo] changing parameters of modi does not store (Issue #823) 
I made a new release which should fix this issue.
@pvklink Could you please update and confirm the issue is solved for you now?

**Comment by lanieuwe** [comment]
Thank you Niels!
It works fine now!
